# Generated by Django 5.2.12 on 2026-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseSpecialtyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(help_text='Name of the disease as output by the PredictaCare AI.', max_length=200, unique=True)),
                ('specialty_name', models.CharField(help_text='Which doctor specialty to consult for this disease (e.g. Dermatologist).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
