# Generated by Django 5.2.12 on 2026-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='predicted_disease',
            field=models.CharField(blank=True, help_text='AI-predicted disease based on symptoms', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='prediction_confidence',
            field=models.FloatField(blank=True, help_text='Prediction confidence percentage (0-100)', null=True),
        ),
    ]
