# Generated by Django 5.2.12 on 2026-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_symptom_predicted_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='selected_symptoms',
            field=models.TextField(blank=True, help_text='Validated symptom list used for ML (stored as JSON/text)', null=True),
        ),
    ]
