# Generated by Django 5.2.12 on 2026-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_symptom_selected_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='selected_symptoms',
        ),
        migrations.AlterField(
            model_name='symptom',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='medicines_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='prediction_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
