# Generated by Django 5.2.12 on 2026-03-22 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_profile_image'),
        ('patient', '0005_diseasecatalog_patient_family_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoraccesslog',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_accesses', to='doctor.doctor'),
        ),
    ]
