# Generated by Django 5.2.12 on 2026-03-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('patient', '0007_familyjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_method', models.CharField(choices=[('PERSONAL', 'Personal ID'), ('FAMILY', 'Family ID'), ('EXPANDED', 'Expanded from Personal')], max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.family')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_accesses', to='hospital.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
            ],
        ),
    ]
