# Generated by Django 5.2.12 on 2026-03-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_hospitalaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyjoinrequest',
            name='custom_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
