# Generated by Django 5.2.12 on 2026-03-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_consultationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireviewlog',
            name='new_catalog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireviewlog',
            name='new_diagnosis_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aireviewlog',
            name='previous_catalog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireviewlog',
            name='previous_diagnosis_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_mode',
            field=models.CharField(blank=True, choices=[('IN_PERSON', 'In Person'), ('ONLINE', 'Online')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='consultation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='created_by_ai_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='diagnosis_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='doctor_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='follow_up_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='is_finalized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='visible_to_patient',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20),
        ),
    ]
