# Generated by Django 5.2.12 on 2026-03-23 04:57

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_aireviewlog_new_catalog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrecord',
            name='prescription_document',
            field=models.FileField(blank=True, null=True, upload_to=patient.models.prescription_upload_path),
        ),
    ]
