# Generated by Django 5.2.12 on 2026-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_consultationrecord_prescription_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrecord',
            name='diagnosis_summary',
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='diagnosis_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='doctor_modified_diagnosis_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
