# Generated by Django 5.2.12 on 2026-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_consultationrecord_diagnosis_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link_or_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_requested_by',
            field=models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
