# Generated by Django 5.2.12 on 2026-04-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctoravailabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailabilityslot',
            name='visit_mode',
            field=models.CharField(blank=True, choices=[('IN_PERSON', 'In Person'), ('ONLINE', 'Online / Video')], max_length=15, null=True),
        ),
    ]
