# Generated by Django 5.2.12 on 2026-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctorleave_doctorweeklyavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorweeklyavailability',
            name='interval_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
